name: flutter_boiler
description: Flutter Boilerplate Project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  http: ^0.13.5
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  image_network: ^2.5.1
  localstorage: ^4.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  faker: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Euclid Circular B
      fonts:
        - asset: lib/presentation/assets/fonts/Euclid-Circular-B-Regular.ttf
        - asset: lib/presentation/assets/fonts/Euclid-Circular-B-Light.ttf
          weight: 400
        - asset: lib/presentation/assets/fonts/Euclid-Circular-B-Bold.ttf
          weight: 700
        - asset: lib/presentation/assets/fonts/Euclid-Circular-B-SemiBold.ttf
          weight: 600
        - asset: lib/presentation/assets/fonts/Euclid-Circular-B-Medium.ttf
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
